import { ProjectTemplate } from './types';

export const templates: ProjectTemplate[] = [
  {
    id: 'product-launch',
    name: 'Product Launch',
    description: 'Complete product launch from planning to post-launch',
    icon: '🚀',
    phases: [
      {
        id: 'planning',
        name: 'Planning & Strategy',
        description: 'Define goals, audience, and strategy',
        order: 0,
        color: '#FF1B8D',
      },
      {
        id: 'build',
        name: 'Build & Create',
        description: 'Develop product and marketing materials',
        order: 1,
        color: '#9D4EDD',
      },
      {
        id: 'launch',
        name: 'Launch Day',
        description: 'Execute launch and monitor',
        order: 2,
        color: '#39FF14',
      },
      {
        id: 'post-launch',
        name: 'Post-Launch',
        description: 'Analyze results and iterate',
        order: 3,
        color: '#00D9FF',
      },
    ],
    suggestedTasks: [
      { title: 'Define target audience', description: '', energyLevel: 'medium', estimatedHours: 2, difficulty: 'medium', isHyperfocus: false, isQuickWin: false, dependencies: [], completed: false },
      { title: 'Create marketing plan', description: '', energyLevel: 'high', estimatedHours: 4, difficulty: 'hard', isHyperfocus: true, isQuickWin: false, dependencies: [], completed: false },
      { title: 'Design landing page', description: '', energyLevel: 'high', estimatedHours: 8, difficulty: 'hard', isHyperfocus: true, isQuickWin: false, dependencies: [], completed: false },
      { title: 'Write launch email', description: '', energyLevel: 'medium', estimatedHours: 2, difficulty: 'easy', isHyperfocus: false, isQuickWin: true, dependencies: [], completed: false },
      { title: 'Schedule social posts', description: '', energyLevel: 'low', estimatedHours: 1, difficulty: 'easy', isHyperfocus: false, isQuickWin: true, dependencies: [], completed: false },
    ],
  },
  {
    id: 'content-series',
    name: 'Content Series',
    description: 'Plan and execute a content campaign',
    icon: '📝',
    phases: [
      {
        id: 'research',
        name: 'Research & Planning',
        description: 'Topic research and content calendar',
        order: 0,
        color: '#FF1B8D',
      },
      {
        id: 'create',
        name: 'Content Creation',
        description: 'Write, design, and produce content',
        order: 1,
        color: '#9D4EDD',
      },
      {
        id: 'publish',
        name: 'Publishing',
        description: 'Schedule and distribute content',
        order: 2,
        color: '#39FF14',
      },
      {
        id: 'promote',
        name: 'Promotion',
        description: 'Amplify and engage',
        order: 3,
        color: '#00D9FF',
      },
    ],
    suggestedTasks: [
      { title: 'Brainstorm topics', description: '', energyLevel: 'high', estimatedHours: 2, difficulty: 'medium', isHyperfocus: false, isQuickWin: false, dependencies: [], completed: false },
      { title: 'Create content calendar', description: '', energyLevel: 'medium', estimatedHours: 1, difficulty: 'easy', isHyperfocus: false, isQuickWin: true, dependencies: [], completed: false },
      { title: 'Write first 3 posts', description: '', energyLevel: 'high', estimatedHours: 6, difficulty: 'medium', isHyperfocus: true, isQuickWin: false, dependencies: [], completed: false },
      { title: 'Design graphics', description: '', energyLevel: 'medium', estimatedHours: 3, difficulty: 'medium', isHyperfocus: false, isQuickWin: false, dependencies: [], completed: false },
      { title: 'Set up email automation', description: '', energyLevel: 'low', estimatedHours: 2, difficulty: 'easy', isHyperfocus: false, isQuickWin: true, dependencies: [], completed: false },
    ],
  },
  {
    id: 'website-redesign',
    name: 'Website Redesign',
    description: 'Complete website overhaul',
    icon: '🎨',
    phases: [
      {
        id: 'discovery',
        name: 'Discovery',
        description: 'Research and requirements',
        order: 0,
        color: '#FF1B8D',
      },
      {
        id: 'design',
        name: 'Design',
        description: 'UI/UX and visual design',
        order: 1,
        color: '#9D4EDD',
      },
      {
        id: 'development',
        name: 'Development',
        description: 'Build and integrate',
        order: 2,
        color: '#39FF14',
      },
      {
        id: 'launch',
        name: 'Launch',
        description: 'Test, deploy, and monitor',
        order: 3,
        color: '#00D9FF',
      },
    ],
    suggestedTasks: [
      { title: 'Audit current site', description: '', energyLevel: 'medium', estimatedHours: 3, difficulty: 'medium', isHyperfocus: false, isQuickWin: false, dependencies: [], completed: false },
      { title: 'Create wireframes', description: '', energyLevel: 'high', estimatedHours: 6, difficulty: 'hard', isHyperfocus: true, isQuickWin: false, dependencies: [], completed: false },
      { title: 'Design homepage', description: '', energyLevel: 'high', estimatedHours: 8, difficulty: 'hard', isHyperfocus: true, isQuickWin: false, dependencies: [], completed: false },
      { title: 'Set up dev environment', description: '', energyLevel: 'low', estimatedHours: 1, difficulty: 'easy', isHyperfocus: false, isQuickWin: true, dependencies: [], completed: false },
      { title: 'Configure hosting', description: '', energyLevel: 'low', estimatedHours: 2, difficulty: 'medium', isHyperfocus: false, isQuickWin: true, dependencies: [], completed: false },
    ],
  },
];
