import { Project, CrewTask, ADHDData, EnergyLevel } from '../types';
import { saveProjects, saveCrewTasks, saveADHDData, markDemoDataLoaded } from './storage';

export const generateDemoData = async () => {
  const today = new Date();
  const yesterday = new Date(today);
  yesterday.setDate(yesterday.getDate() - 1);
  const nextWeek = new Date(today);
  nextWeek.setDate(nextWeek.getDate() + 7);

  // Demo Projects
  const demoProjects: Project[] = [
    {
      id: 'demo-1',
      name: 'Launch The dAItaniverse',
      description: 'Complete platform launch - AI-powered creative ecosystem for ADHD entrepreneurs',
      status: 'live',
      startDate: yesterday.toISOString().split('T')[0],
      targetDate: new Date(today.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      progress: 45,
      tasksTotal: 12,
      tasksCompleted: 5,
      priority: 'high',
      tags: ['Product', 'Launch', 'Platform'],
      createdAt: yesterday.toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  // Demo Crew Tasks for "Launch The dAItaniverse" - 4 phases, 12 tasks
  const demoTasks: CrewTask[] = [
    // PHASE 1: Planning & Strategy
    {
      id: 'task-1',
      title: 'Define platform vision and roadmap',
      description: 'Create comprehensive vision doc and 90-day launch plan',
      phaseId: 'phase-1-planning',
      energyLevel: 'high',
      estimatedHours: 4,
      difficulty: 'hard',
      isHyperfocus: true,
      isQuickWin: false,
      dependencies: [],
      completed: true,
      order: 0,
      createdAt: yesterday.toISOString(),
      timeSpent: 180,
      scheduledDate: yesterday.toISOString().split('T')[0],
      completedAt: yesterday.toISOString(),
    },
    {
      id: 'task-2',
      title: 'Research target audience needs',
      description: 'Conduct surveys and interviews with ADHD entrepreneurs',
      phaseId: 'phase-1-planning',
      energyLevel: 'medium',
      estimatedHours: 3,
      difficulty: 'medium',
      isHyperfocus: false,
      isQuickWin: false,
      dependencies: [],
      completed: true,
      order: 1,
      createdAt: yesterday.toISOString(),
      timeSpent: 150,
      scheduledDate: yesterday.toISOString().split('T')[0],
      completedAt: yesterday.toISOString(),
    },
    {
      id: 'task-3',
      title: 'Design system architecture',
      description: 'Technical blueprint for AI integration and scalability',
      phaseId: 'phase-1-planning',
      energyLevel: 'high',
      estimatedHours: 5,
      difficulty: 'hard',
      isHyperfocus: true,
      isQuickWin: false,
      dependencies: [],
      completed: true,
      order: 2,
      createdAt: yesterday.toISOString(),
      timeSpent: 240,
      scheduledDate: yesterday.toISOString().split('T')[0],
      completedAt: yesterday.toISOString(),
    },
    // PHASE 2: Development
    {
      id: 'task-4',
      title: 'Build core AI integration',
      description: 'Implement Claude API with creative assistant features',
      phaseId: 'phase-2-development',
      energyLevel: 'high',
      estimatedHours: 6,
      difficulty: 'hard',
      isHyperfocus: true,
      isQuickWin: false,
      dependencies: [],
      completed: true,
      order: 3,
      createdAt: today.toISOString(),
      timeSpent: 300,
      scheduledDate: today.toISOString().split('T')[0],
      completedAt: today.toISOString(),
    },
    {
      id: 'task-5',
      title: 'Create user dashboard UI',
      description: 'Design and build main dashboard with dark mode',
      phaseId: 'phase-2-development',
      energyLevel: 'high',
      estimatedHours: 4,
      difficulty: 'medium',
      isHyperfocus: true,
      isQuickWin: false,
      dependencies: [],
      completed: true,
      order: 4,
      createdAt: today.toISOString(),
      timeSpent: 200,
      scheduledDate: today.toISOString().split('T')[0],
      completedAt: today.toISOString(),
    },
    {
      id: 'task-6',
      title: 'Implement project management features',
      description: 'Task tracking, energy matching, timeline views',
      phaseId: 'phase-2-development',
      energyLevel: 'medium',
      estimatedHours: 5,
      difficulty: 'hard',
      isHyperfocus: false,
      isQuickWin: false,
      dependencies: [],
      completed: false,
      order: 5,
      createdAt: today.toISOString(),
      timeSpent: 180,
      scheduledDate: today.toISOString().split('T')[0],
    },
    // PHASE 3: Content & Launch Prep
    {
      id: 'task-7',
      title: 'Write launch announcement',
      description: 'Compelling copy for social media and email campaign',
      phaseId: 'phase-3-launch-prep',
      energyLevel: 'high',
      estimatedHours: 2,
      difficulty: 'medium',
      isHyperfocus: true,
      isQuickWin: false,
      dependencies: [],
      completed: false,
      order: 6,
      createdAt: today.toISOString(),
      timeSpent: 0,
      scheduledDate: new Date(today.getTime() + 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      scheduledTime: '10:00',
    },
    {
      id: 'task-8',
      title: 'Create demo video',
      description: 'Screen recording walkthrough with voiceover',
      phaseId: 'phase-3-launch-prep',
      energyLevel: 'high',
      estimatedHours: 3,
      difficulty: 'medium',
      isHyperfocus: true,
      isQuickWin: false,
      dependencies: [],
      completed: false,
      order: 7,
      createdAt: today.toISOString(),
      timeSpent: 0,
      scheduledDate: new Date(today.getTime() + 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      scheduledTime: '14:00',
    },
    {
      id: 'task-9',
      title: 'Set up analytics and tracking',
      description: 'Install GA4, Mixpanel, and error monitoring',
      phaseId: 'phase-3-launch-prep',
      energyLevel: 'low',
      estimatedHours: 1,
      difficulty: 'easy',
      isHyperfocus: false,
      isQuickWin: true,
      dependencies: [],
      completed: false,
      order: 8,
      createdAt: today.toISOString(),
      timeSpent: 0,
      scheduledDate: new Date(today.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      scheduledTime: '11:00',
    },
    // PHASE 4: Launch & Scale
    {
      id: 'task-10',
      title: 'Launch on Product Hunt',
      description: 'Coordinate launch day activities and community engagement',
      phaseId: 'phase-4-launch',
      energyLevel: 'high',
      estimatedHours: 8,
      difficulty: 'hard',
      isHyperfocus: true,
      isQuickWin: false,
      dependencies: [],
      completed: false,
      order: 9,
      createdAt: today.toISOString(),
      timeSpent: 0,
      scheduledDate: new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      scheduledTime: '00:01',
    },
    {
      id: 'task-11',
      title: 'Onboard first 100 users',
      description: 'Personal outreach and white-glove onboarding',
      phaseId: 'phase-4-launch',
      energyLevel: 'medium',
      estimatedHours: 10,
      difficulty: 'medium',
      isHyperfocus: false,
      isQuickWin: false,
      dependencies: [],
      completed: false,
      order: 10,
      createdAt: today.toISOString(),
      timeSpent: 0,
      scheduledDate: new Date(today.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    },
    {
      id: 'task-12',
      title: 'Collect and implement feedback',
      description: 'Iterate based on early user insights',
      phaseId: 'phase-4-launch',
      energyLevel: 'low',
      estimatedHours: 4,
      difficulty: 'easy',
      isHyperfocus: false,
      isQuickWin: true,
      dependencies: [],
      completed: false,
      order: 11,
      createdAt: today.toISOString(),
      timeSpent: 0,
      scheduledDate: new Date(today.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    },
  ];

  // Demo ADHD Data
  const demoADHDData: ADHDData = {
    brainDumps: [
      {
        id: 'dump-1',
        content: 'Need to follow up with Sarah about collaboration',
        timestamp: new Date(today.getTime() - 2 * 60 * 60 * 1000).toISOString(),
        converted: false,
        archived: false,
      },
      {
        id: 'dump-2',
        content: 'Idea: Template library for common project types',
        timestamp: new Date(today.getTime() - 5 * 60 * 60 * 1000).toISOString(),
        converted: false,
        archived: false,
      },
    ],
    energyLogs: [
      {
        id: 'energy-1',
        timestamp: new Date(today.setHours(9, 0, 0, 0)).toISOString(),
        level: 'high',
      },
      {
        id: 'energy-2',
        timestamp: new Date(today.setHours(14, 0, 0, 0)).toISOString(),
        level: 'medium',
      },
    ],
    hyperfocusSessions: [
      {
        id: 'focus-1',
        startTime: new Date(yesterday.setHours(10, 0, 0, 0)).toISOString(),
        endTime: new Date(yesterday.setHours(13, 30, 0, 0)).toISOString(),
        duration: 210,
        trigger: 'Interesting problem',
        taskType: 'Coding',
        taskName: 'Build new feature',
        productivityRating: 5,
        notes: 'Got completely in the zone!',
      },
    ],
  };

  // Save all demo data
  await saveProjects(demoProjects);
  await saveCrewTasks(demoTasks);
  await saveADHDData(demoADHDData);
  await markDemoDataLoaded();
};
